### ISSUE TITLE
Missing constructors for MOBIL and Tim2DDriver

### ISSUE THREAD

**Issue by raunakbh92** [sisl/AutomotiveSimulator.jl#10]
Looks like the constructor for MOBIL was removed in this [commit](https://github.com/sisl/AutomotiveDrivingModels.jl/commit/53d97386a80303e1672be1547335869d9d9f122d#diff-e9f6077f7fc52c4e276ac7dbc408f107) in AutomotiveDrivingModels.jl. What was the reason for this? Has the interface for working with MOBIl and Tim2DDriver changed in some way that does not necessitate these constructors anymore?

**Comment by MaximeBouton** [comment]
The constructor is not missing, but it has changed, the `timestep` argument has been removed since it is not used anymore. It was there because those driver models were storing a `QueueRecord` internally. 

The constructor is now automatically defined by the `@with_kw` macro. 

I just updated the docstrings they were not accurate.

**Comment by raunakbh92** [comment]
Great! Thanks a lot Maxime. Closing this issue.
